version: '3.3'

services:

  productiondb:
    env_file: .env
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
    volumes:
      - productiondata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  productionvault:
    depends_on:
      - productiondb

  backup:
    env_file: .env
    build: .
    restart: always
    volumes:
      - productiondata:/dbdata
      - ${BACKUP_LOCATION:-.}:/backup
    command: bin/backup.sh

volumes:
  productiondata: